const projects = [
 {name:'ALKAHRABA / Saudi Energy',accent:'#18a69a',type:'NATIONAL UTILITY · iOS',description:'Contributed to the customer-facing app for Saudi Electricity Company, delivering clear bill journeys, secure payments, consumption analytics, account services, requests, and customer support. Modernized legacy modules and integrated enterprise APIs for a high-traffic platform.',tags:['Swift','UIKit','Billing & Payments','Consumption Analytics','Enterprise APIs','Arabic RTL','Performance'],url:'https://apps.apple.com/sa/app/saudi-energy/id1502975624',featured:true,galleryBase:'assets/projects/alkahraba',gallery:['01-home.jpg','02-services.jpg','03-payment.jpg','04-consumption.jpg','06-menu.jpg']},
 {name:'Ifta Employee',accent:'#73a875',type:'GOVERNMENT · EMPLOYEE OPERATIONS',description:'A secure workforce platform for attendance, biometric and location-aware check-ins, field rounds, administrative movements, operational alerts, assignments, and internal communication.',tags:['Clean Architecture','Biometrics','Location Services','Secure APIs','Arabic RTL','Operational Workflows'],icon:'assets/projects/icons/ifta-employee.png',galleryBase:'assets/projects/ifta-employee',gallery:['07-welcome.jpg','06-assignments.jpg','05-location.jpg','04-rounds.jpg','03-activity.jpg','02-attendance.jpg','01-alerts.jpg']},
 {name:'King Abdullah Sunnah Encyclopedia',accent:'#b98a37',type:'ISLAMIC KNOWLEDGE · HADITH RESEARCH',description:'جامع الملك عبدالله للسنة النبوية is a comprehensive digital Hadith library for exploring books, narrations, chains of transmission, narrators, explanations, indexes, dictionaries, and scholarly services. The delivered product spans 7 core sections, 30 implemented features, and 76 documented screens.',tags:['Swift','UIKit','Arabic RTL','Advanced Search','Digital Library','Hadith Research','Content Navigation'],url:'https://apps.apple.com/sa/app/%D8%AC%D8%A7%D9%85%D8%B9-%D8%A7%D9%84%D9%85%D9%84%D9%83-%D8%B9%D8%A8%D8%AF%D8%A7%D9%84%D9%84%D9%87/id1637888723',reportUrl:'assets/reports/king-abdullah-sunnah-app-report.pdf',icon:'assets/projects/icons/king-abdullah-sunnah.jpg',galleryBase:'assets/projects/king-abdullah-sunnah',gallery:['01-library.jpg','02-reading.jpg','03-tools.jpg','04-rare-words.jpg','05-quranic-meaning.jpg','06-wellbeing.jpg','07-narrator-verification.jpg','08-comparison.jpg','09-narrators.jpg','10-terminology.jpg']},
 {name:'فتوي اسألني Fatwa AskMe',accent:'#83b28a',type:'GOVERNMENT · ISLAMIC KNOWLEDGE',description:'A public-service iOS platform connecting users worldwide with official scholarly guidance from Saudi Arabia. Built searchable fatwa discovery, question submission, request tracking, favorites, notifications, and detailed Arabic answer experiences.',tags:['Swift','MVVM','Arabic RTL','REST APIs','Search','Notifications'],icon:'assets/projects/icons/fatwa-askme.png',galleryBase:'assets/projects/ask-me-fatwa',gallery:['01-search.jpg','02-favorites.jpg','03-results.jpg','04-answered.jpg','05-pending.jpg','06-detail.jpg','07-ask.jpg','08-topics.jpg','09-feed.jpg','10-login.jpg','11-splash.jpg']},
 {name:'Sheikh Fatwa',accent:'#83b28a',type:'GOVERNMENT · SECURE SCHOLAR WORKFLOW',description:'A restricted-access iOS workspace for senior scholars and institutional reviewers. Built secure question queues, advanced search, operational statistics, status tracking, answer drafting, review and approval workflows, and controlled transfers between specialist teams.',tags:['Swift','VIPER','Access Control','Secure Workflows','Arabic RTL','Review & Approval'],galleryBase:'assets/projects/sheikh-fatwa',gallery:['01-inquiry.jpg','02-dashboard.jpg','03-status.jpg','04-review.jpg','05-search.jpg','06-workflows.jpg']},
 {name:'Yelloday',accent:'#f2c800',type:'COMMERCE · REWARDS & GIFTING',description:'A gamified commerce experience where customers discover premium gifts, purchase entries, track their chances, complete secure checkout, and manage rewards from one account-centered journey.',tags:['Swift','UIKit','Clean Architecture','Payments','Localization','Gamification'],url:'https://apps.apple.com/sa/app/yelloday/id6754116669',icon:'assets/projects/icons/yelloday.png',galleryBase:'assets/projects/yelloday',gallery:['01-sign-in.jpg','02-gifts.jpg','03-chances.jpg','04-onboarding.jpg','05-checkout.jpg','06-account.jpg','07-register.jpg']},
{name:'Kyan Quality',accent:'#25a9c5',type:'ENTERPRISE · QUALITY & COMPLIANCE',description:'An enterprise quality-management platform for Kyan Coffee, giving operations teams a consistent way to monitor branches, configure roles, standardize violations, review compliance, and export actionable reports across more than 400 locations.',tags:['Swift','UIKit','Enterprise','Role-Based Access','Quality Audits','Reporting'],url:'https://apps.apple.com/sa/app/kyan-quality/id1551518151',icon:'assets/projects/icons/kyan-quality.png',galleryBase:'assets/projects/kyan-quality',gallery:['01-login.jpg','02-branches.jpg','03-navigation.jpg','04-branch-data.jpg','05-review-violations.jpg','06-settings.jpg','07-permissions.jpg','08-quality-rules.jpg','09-reports.jpg']},
 {name:'Carek',accent:'#168fd1',type:'ON-DEMAND · CAR CARE',description:'A complete car-care marketplace that lets customers discover services, book home or branch visits, purchase wash packages, and manage payments through an integrated wallet. Built around a clear Arabic journey from service selection to account management.',tags:['Swift','UIKit','MVVM','Maps & Location','Booking Flows','Digital Wallet'],url:'https://apps.apple.com/sa/app/carek-%D9%83%D8%A7%D8%B1%D9%83/id6737919831',icon:'assets/projects/icons/carek.png',galleryBase:'assets/projects/carek',gallery:['01-home.jpg','02-book-service.jpg','03-packages.jpg','04-wallet.jpg','05-account.jpg','06-more.jpg']},
 {name:'Carek Provider',accent:'#3978d1',type:'ON-DEMAND · SERVICE OPERATIONS',description:'The provider-facing side of the Carek ecosystem, designed to help car-care teams receive service requests, coordinate appointments, manage availability, track job progress, and keep daily operations moving from one focused mobile workspace.',tags:['Swift','UIKit','Provider App','Operational Workflows','Booking Management','Maps & Location','Arabic RTL'],url:'https://testflight.apple.com/join/hsMJp6vg',urlLabel:'TestFlight',icon:'assets/projects/icons/carek-provider.png',galleryBase:'assets/projects/carek-provider',gallery:['01-launch.jpg','02-login.jpg','03-orders.jpg','04-order-details.jpg','05-notifications.jpg']},
 {name:'Aljoud',accent:'#159a8c',type:'EDUCATION · DIGITAL LEARNING',description:'An integrated learning marketplace connecting university students with structured courses, rich study materials, interactive quizzes, educational offers, and flexible purchasing journeys.',tags:['Swift','UIKit','MVVM','REST APIs','PDFKit','In-App Learning'],url:'https://apps.apple.com/sa/app/aljoud/id1604452873',icon:'assets/projects/icons/aljoud.png',galleryBase:'assets/projects/aljoud',gallery:['01-universities.jpg','02-specialties.jpg','03-courses.jpg','04-course-details.jpg','05-my-courses.jpg','06-quiz.jpg','07-pdf-study.jpg','08-offers.jpg','09-cart.jpg','10-more.jpg']},
 {name:'Bunny Box',accent:'#7ccce8',type:'COMMERCE · PERSONALIZED GIFTING',description:'A personalized gifting experience that helps customers discover curated collections, build occasion-based boxes, manage recipient preferences, and explore limited-time offers through a playful end-to-end shopping journey.',tags:['Swift','UIKit','E-Commerce','Personalization','Payments','REST APIs'],url:'https://apps.apple.com/sa/app/bunny-box/id6471868376',icon:'assets/projects/icons/bunny-box.png',galleryBase:'assets/projects/bunny-box',gallery:['01-launch.jpg','02-personalities.jpg','03-collections.jpg','04-build-box.jpg','05-profile.jpg','06-sign-in.jpg','07-sign-up.jpg','08-mystery-categories.jpg','09-offers.jpg']}
];
const galleryMarkup=p=>{const last=p.gallery.length-1;const next=p.gallery.length>1?1:0;return `<div class="project-gallery" data-gallery data-index="0" data-base="${p.galleryBase}" data-name="${p.name}" tabindex="0"><div class="gallery-stage"><img class="gallery-peek gallery-peek-prev" src="${p.galleryBase}/${p.gallery[last]}" alt="" aria-hidden="true"><img class="gallery-main" src="${p.galleryBase}/${p.gallery[0]}" alt="${p.name} app screen 1 of ${p.gallery.length}"><img class="gallery-peek gallery-peek-next" src="${p.galleryBase}/${p.gallery[next]}" alt="" aria-hidden="true"><button class="gallery-arrow prev" type="button" aria-label="Previous ${p.name} screenshot">‹</button><button class="gallery-arrow next" type="button" aria-label="Next ${p.name} screenshot">›</button></div><div class="gallery-footer"><span class="gallery-count">01 / ${String(p.gallery.length).padStart(2,'0')}</span><div class="gallery-dots" aria-label="Choose ${p.name} screenshot">${p.gallery.map((_,n)=>`<button type="button" data-slide="${n}" class="${n===0?'active':''}" aria-label="Show screenshot ${n+1}" aria-current="${n===0?'true':'false'}"></button>`).join('')}</div></div><script type="application/json" class="gallery-data">${JSON.stringify(p.gallery)}</script></div>`};
const projectLinks=p=>`<div class="project-links">${p.url?`<a class="project-link" href="${p.url}" target="_blank" rel="noopener noreferrer">${p.urlLabel||'App Store'} ↗</a>`:''}${p.reportUrl?`<button class="project-link report-link" type="button" data-report="${p.reportUrl}" data-report-title="${p.name} project report">Project report ↗</button>`:''}</div>`;
document.querySelector('#project-list').innerHTML=projects.map((p,i)=>{
 const number=String(i+1).padStart(2,'0');
 if(p.featured)return `<article class="project featured showcase" style="--project-accent:${p.accent}"><div class="project-copy"><span class="meta">${number} / ${p.type}</span><span class="featured-label">Featured project</span><h3>${p.name}</h3><p>${p.description}</p><div class="tags">${p.tags.slice(0,6).map(t=>`<span>${t}</span>`).join('')}${p.tags.length>6?`<span>+${p.tags.length-6} more</span>`:''}</div>${projectLinks(p)}</div>${galleryMarkup(p)}</article>`;
 const shownTags=p.tags.slice(0,5);
 const initials=p.name.split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase();
 return `<article class="project project-card" data-project-card="${i}" style="--project-accent:${p.accent}"><div class="project-card-top"><button class="project-card-head project-open" type="button" data-project="${i}" aria-label="Open ${p.name} project details"><span class="project-icon" aria-hidden="true">${p.icon?`<img src="${p.icon}" alt="">`:initials}</span><span class="project-title"><span class="meta">${p.type}</span><strong>${p.name}</strong></span></button>${projectLinks(p)}</div><p>${p.description}</p><div class="tags">${shownTags.map(t=>`<span>${t}</span>`).join('')}${p.tags.length>shownTags.length?`<span>+${p.tags.length-shownTags.length} more</span>`:''}</div>${p.gallery?galleryMarkup(p):'<div class="project-private-preview"><span>Private product</span><small>Screens available on request</small></div>'}</article>`;
}).join('');

const projectViewer=document.createElement('div');
projectViewer.className='project-viewer';
projectViewer.setAttribute('aria-hidden','true');
projectViewer.innerHTML='<div class="project-dialog" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title"><button type="button" class="project-dialog-close" aria-label="Close project details">×</button><div class="project-dialog-content"></div></div>';
document.body.append(projectViewer);
const projectDialogContent=projectViewer.querySelector('.project-dialog-content');
const projectDialogClose=projectViewer.querySelector('.project-dialog-close');
let projectTrigger=null;
function closeProject(){projectViewer.classList.remove('open');projectViewer.setAttribute('aria-hidden','true');document.body.classList.remove('project-open');projectDialogContent.innerHTML='';projectTrigger?.focus();}
function openProject(index,trigger){
 const p=projects[Number(index)];projectTrigger=trigger;
 projectViewer.style.setProperty('--project-accent',p.accent);
 projectDialogContent.innerHTML=`<div class="project-dialog-gallery">${p.gallery?galleryMarkup(p):'<div class="project-dialog-empty">Private product · Screens unavailable</div>'}</div><div class="project-dialog-copy"><span class="meta">${p.type}</span><h2 id="project-dialog-title">${p.name}</h2><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>${projectLinks(p)}</div>`;
 projectDialogContent.querySelectorAll('[data-gallery]').forEach(initGallery);
 projectViewer.classList.add('open');projectViewer.setAttribute('aria-hidden','false');document.body.classList.add('project-open');projectDialogClose.focus();
}
document.querySelectorAll('.project-open').forEach(button=>button.addEventListener('click',()=>openProject(button.dataset.project,button)));
document.querySelectorAll('[data-project-card]').forEach(card=>card.addEventListener('click',event=>{
 if(event.target.closest('a,button,.project-gallery'))return;
 openProject(card.dataset.projectCard,card.querySelector('.project-open'));
}));
projectDialogClose.addEventListener('click',closeProject);
projectViewer.addEventListener('click',event=>{if(event.target===projectViewer)closeProject();});

const reportViewer=document.createElement('div');
reportViewer.className='report-viewer';
reportViewer.setAttribute('aria-hidden','true');
reportViewer.innerHTML='<div class="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-title"><header><h2 id="report-title">Project report</h2><button type="button" class="report-close" aria-label="Close project report">×</button></header><iframe title="Project report" loading="lazy"></iframe></div>';
document.body.append(reportViewer);
const reportFrame=reportViewer.querySelector('iframe');
const reportTitle=reportViewer.querySelector('#report-title');
const reportClose=reportViewer.querySelector('.report-close');
let reportTrigger=null;
function closeReport(){reportViewer.classList.remove('open');reportViewer.setAttribute('aria-hidden','true');reportFrame.removeAttribute('src');document.body.classList.remove('report-open');reportTrigger?.focus();}
document.querySelectorAll('[data-report]').forEach(button=>button.addEventListener('click',()=>{reportTrigger=button;reportTitle.textContent=button.dataset.reportTitle;reportFrame.src=`${button.dataset.report}#toolbar=1&navpanes=0&view=FitH`;reportViewer.classList.add('open');reportViewer.setAttribute('aria-hidden','false');document.body.classList.add('report-open');reportClose.focus();}));
reportClose.addEventListener('click',closeReport);
reportViewer.addEventListener('click',event=>{if(event.target===reportViewer)closeReport();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&reportViewer.classList.contains('open'))closeReport();if(event.key==='Escape'&&projectViewer.classList.contains('open'))closeProject();});

function initGallery(gallery){
 const images=JSON.parse(gallery.querySelector('.gallery-data').textContent);
 const imageUrls=images.map(file=>`${gallery.dataset.base}/${file}`);
 const image=gallery.querySelector('.gallery-main');
 const previousPreview=gallery.querySelector('.gallery-peek-prev');
 const nextPreview=gallery.querySelector('.gallery-peek-next');
 const count=gallery.querySelector('.gallery-count');
 const dots=[...gallery.querySelectorAll('[data-slide]')];
 const preload=src=>{const cached=new Image();cached.decoding='async';cached.src=src;};
 const warmAround=index=>[-2,-1,0,1,2].forEach(offset=>preload(imageUrls[(index+offset+images.length)%images.length]));
 const show=index=>{
  const next=(index+images.length)%images.length;
  gallery.dataset.index=next;
  image.src=imageUrls[next];
  image.alt=`${gallery.dataset.name} app screen ${next+1} of ${images.length}`;
  previousPreview.src=imageUrls[(next-1+images.length)%images.length];
  nextPreview.src=imageUrls[(next+1)%images.length];
  count.textContent=`${String(next+1).padStart(2,'0')} / ${String(images.length).padStart(2,'0')}`;
  dots.forEach((dot,i)=>{dot.classList.toggle('active',i===next);dot.setAttribute('aria-current',i===next?'true':'false');});
  warmAround(next);
 };
 gallery.querySelector('.prev').addEventListener('click',()=>show(Number(gallery.dataset.index)-1));
 gallery.querySelector('.next').addEventListener('click',()=>show(Number(gallery.dataset.index)+1));
 dots.forEach(dot=>dot.addEventListener('click',()=>show(Number(dot.dataset.slide))));
 gallery.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')show(Number(gallery.dataset.index)-1);if(event.key==='ArrowRight')show(Number(gallery.dataset.index)+1);});
 warmAround(0);
 const warmAll=()=>imageUrls.forEach(preload);
 'requestIdleCallback' in window?requestIdleCallback(warmAll,{timeout:1800}):setTimeout(warmAll,700);
}
document.querySelectorAll('[data-gallery]').forEach(initGallery);
const roles=[
 {period:'Oct 2024 — Present',company:'2P Perfect Presentation',mark:'2P',logo:'assets/companies/2p.png',title:'Senior iOS Engineer',place:'Riyadh',current:true,highlights:['Own architecture and technical direction across a portfolio of secure government iOS applications.','Set engineering standards through code reviews, shared guidelines, and hands-on mentoring.','Modernize legacy modules, monitor production health, and coordinate delivery across product, design, backend, and QA.'],tags:['Leadership','Architecture','Government']},
 {period:'Aug 2023 — May 2026',company:'AKNANA SOLUTIONS',mark:'AK',markClass:'aknana-mark',logo:'assets/companies/aknana.png',title:'Technical Product Manager · Senior iOS Developer',place:'Part-time · Riyadh',highlights:['Progressed from sole iOS engineer across four products into technical product management.','Led delivery across seven mobile and web products with a 15-person design, engineering, and QA team.','Defined roadmaps, milestones, and release priorities while keeping technical and product decisions aligned.'],tags:['Product Leadership','iOS Ownership','Cross-functional']},
 {period:'Oct 2022 — Oct 2024',company:'Ebttikar Technology Company',mark:'ET',logo:'assets/companies/ebttikar.png',title:'Senior iOS Developer',place:'Dar Al-Ifta, Riyadh',highlights:['Led three government iOS applications from architecture through production release.','Expanded public, employee, and scholar-facing platforms through structured feature delivery.','Improved Ifta Employee stability through systematic debugging, memory optimization, and release monitoring.'],tags:['Delivery','Stability','Secure Apps']},
 {period:'Oct 2021 — Oct 2022',company:'Saudi Electricity Company',mark:'SEC',logo:'assets/companies/saudi-energy.png',title:'Senior iOS Developer',place:'Riyadh',highlights:['Delivered billing, payment, consumption, and service-request journeys for a national utility platform.','Built internal employee workflows for Bowbti across field and back-office operations.','Modernized legacy UIKit modules and integrated enterprise APIs under strict uptime and security constraints.'],tags:['Utility','Enterprise APIs','Performance']},
 {period:'May 2020 — Oct 2021',company:'Alqemam qTech',mark:'AQ',logo:'assets/companies/alqemam-qtech.png',title:'iOS Developer',place:'Cairo',highlights:['Built modular Swift and UIKit applications across commerce, education, and on-demand services.','Integrated REST APIs, payments, maps, and localized Arabic user journeys.','Collaborated with product and backend teams to deliver production-ready applications.'],tags:['Swift','UIKit','Modular Apps']},
 {period:'Mar 2021 — Mar 2022',company:'Ivan Illich Institute',mark:'III',logo:'assets/companies/ivan-illich.png',title:'Computer Science Instructor',place:'Part-time · Remote',highlights:['Designed and delivered programming and software-engineering courses for aspiring developers.','Taught data structures and core development practices through hands-on software projects.','Mentored learners through practical work and early-career preparation.'],tags:['Teaching','Mentoring','Computer Science']},
 {period:'Jun 2018 — Mar 2019',company:'Alsalil Software House / IT Share Center',mark:'AS',title:'iOS Developer & Instructor',place:'Mansoura',highlights:['Contributed to production iOS applications using Swift and UIKit.','Delivered practical iOS-development training and guided hands-on projects.','Supported developers during the early stages of their mobile-development careers.'],tags:['iOS','Training','Early Career']}
];
document.querySelector('#timeline').innerHTML=roles.map((r,i)=>`<article class="role-card ${r.current?'current':''}" style="--role-index:${i}"><div class="timeline-marker" aria-hidden="true"><span>${String(i+1).padStart(2,'0')}</span></div><div class="role-card-inner"><header class="role-header"><div class="company-mark ${r.markClass||''}" aria-hidden="true">${r.logo?`<img src="${r.logo}" alt="">`:r.mark}</div><div class="role-title"><div class="role-period"><span>${r.period}</span>${r.current?'<em>Current</em>':''}</div><h3>${r.company}</h3><p>${r.title}<span>·</span>${r.place}</p></div></header><ul class="role-highlights">${r.highlights.map(item=>`<li>${item}</li>`).join('')}</ul><div class="role-tags">${r.tags.map(tag=>`<span>${tag}</span>`).join('')}</div></div></article>`).join('');
const roleObserver='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');roleObserver.unobserve(entry.target);}}),{threshold:.16}):null;
document.querySelectorAll('.role-card').forEach(card=>roleObserver?roleObserver.observe(card):card.classList.add('visible'));
const skills=[
 {title:'Native iOS',summary:'Native product engineering across modern and legacy Apple stacks.',items:['Swift','SwiftUI','UIKit','Objective-C','Auto Layout','Push Notifications','Localization & Arabic RTL']},
 {title:'Architecture',summary:'Modular foundations that keep complex products maintainable as they grow.',items:['Clean Architecture','MVVM','VIPER','SOLID','Dependency Injection','Modularization']},
 {title:'Concurrency & performance',summary:'Responsive experiences designed for demanding production workloads.',items:['Swift Concurrency','async/await','Combine','GCD','Memory Management','Instruments']},
 {title:'Networking & data',summary:'Reliable data flows across APIs, live connections, and local persistence.',items:['REST APIs','URLSession','Alamofire','WebSockets','JSON','Core Data']},
 {title:'Security & quality',summary:'Secure application behavior supported by testing and production insight.',items:['Biometrics','Keychain','Role-Based Access','XCTest','Unit Testing','Code Reviews','Crashlytics']},
 {title:'Product & delivery',summary:'Technical leadership that connects product priorities with reliable releases.',items:['Roadmapping','Agile','Cross-functional Delivery','Mentoring','Git','SPM','Fastlane','CI/CD','TestFlight','App Store Connect','Jira','ClickUp']}
];
document.querySelector('#skill-list').innerHTML=skills.map((s,i)=>`<article class="skill"><header><span class="number">${String(i+1).padStart(2,'0')}</span></header><h3>${s.title}</h3><p class="skill-summary">${s.summary}</p><div class="skill-tags">${s.items.map(item=>`<span>${item}</span>`).join('')}</div></article>`).join('');
const themeButton=document.querySelector('#theme');
function setTheme(light){document.body.classList.toggle('light',light);themeButton.setAttribute('aria-label',`Switch to ${light?'dark':'light'} theme`);}
try{setTheme(localStorage.getItem('sayed-theme')==='light');}catch{}
themeButton.addEventListener('click',()=>{const light=!document.body.classList.contains('light');setTheme(light);try{localStorage.setItem('sayed-theme',light?'light':'dark');}catch{}});
document.querySelector('#year').textContent=new Date().getFullYear();
